name: dapackages
description: A Flutter package to automatically update your pubspec dependencies in your project.
version: 1.3.0
homepage: https://github.com/mauriciotogneri/dapackages

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  yaml: ^2.2.1
  http: ^0.12.2